name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: pysquared_zephyr

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: pysquared_zephyr
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: pysquared_zephyr
        shell: bash
        run: |
          west twister -T app -v --inline-logs --integration

#      - name: Twister Tests
#        working-directory: pysquared_zephyr
#        shell: bash
#        run: |
#          if [ "${{ runner.os }}" = "Windows" ]; then
#            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
#          fi
#          west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-uf2
          path: pysquared_zephyr/twister-out/proves_flight_board_v5_rp2350a_m33/zephyr/app.default/zephyr/zephyr.uf2